site_name: onemetric
site_author: Piotr Skalski

nav:
  - Home: index.md
  - API reference:
      - Computer Vision:
          - Object Detection: cv/object_detection.md
          - Utils: cv/utils.md
  - License: LICENSE.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

repo_name: 'SkalskiP/onemetric'
repo_url: 'https://github.com/SkalskiP/onemetric'


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences