site_name: onemetric
site_author: Piotr Skalski

nav:
  - Home: index.md
  - API reference:
      - Computer Vision:
          - Intersection over Union: cv/utils/iou.md
          - Average Precision: cv/object_detection/average_precision.md
          - Confusion Matrix: cv/object_detection/confusion_matrix.md
  - Contribution Guide: CONTRIBUTING.md
  - License: LICENSE.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: 'img/logo.png'
  favicon: 'img/favicon.png'
  features:
    - navigation.expand
  icon:
    repo: fontawesome/brands/github

repo_name: 'SkalskiP/onemetric'
repo_url: 'https://github.com/SkalskiP/onemetric'


markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences