site_name: onemetric
site_author: Piotr Skalski

nav:
  - Home: index.md
  - API reference:
      - Computer Vision:
          - Object Detection: cv/object_detection.md
          - Utils: cv/utils.md
  - License: LICENSE.md

theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'

repo_name: 'SkalskiP/onemetric'
repo_url: 'https://github.com/SkalskiP/onemetric'

markdown_extensions:
  - codehilite