name: docs
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: python tools/autogen.py
      - run: cp README.md docs/index.md
      - run: cp LICENSE.md docs/LICENSE.md
      - run: cp CONTRIBUTING.md docs/CONTRIBUTING.md
      - run: mkdocs gh-deploy --force